
# Twitter Secrets
MY_CONSUMER_KEY        = 'TWITTER_CONSUMER_KEY'
MY_CONSUMER_SECRET     = 'TWITTER_CONSUMER_SECRET'
MY_ACCESS_TOKEN_KEY    = 'TWITTER_ACCESS_TOKEN_KEY'
MY_ACCESS_TOKEN_SECRET = 'TWITTER_ACCESS_TOKEN_SECRET'

# AWS Events Cognito Info
COGNITO_POOL_ID   = "us-east-1_Xuc1O0biz"
COGNITO_CLIENT_ID = "2h40eam2atft40g0c3mlg0aei1"

# AWS Events Portal Secrets
AWS_EVENTS_USERNAME = 'AWS_EVENTS_USERNAME'
AWS_EVENTS_PASSWORD = 'AWS_EVENTS_PASSWORD'

# DynamoDB Tables
SESSION_TABLE = 'DYNAMODB_SESSION_TABLE_NAME'