
# Twitter Secrets
MY_CONSUMER_KEY = 'TWITTER_CONSUMER_KEY'
MY_CONSUMER_SECRET = 'TWITTER_CONSUMER_SECRET'
MY_ACCESS_TOKEN_KEY = 'TWITTER_ACCESS_TOKEN_KEY'
MY_ACCESS_TOKEN_SECRET = 'TWITTER_ACCESS_TOKEN_SECRET'

# re:Invent Portal Secrets
USERNAME = 'REINVENT_PORTAL_USERNAME'
PASSWORD = 'REINVENT_PORTAL_PASSWORD'

# DynamoDB Tables
LOGGING_TABLE = 'DYNAMODB_LOGGING_TABLE_NAME'
SESSION_TABLE = 'DYNAMODB_SESSION_TABLE_NAME'